### ISSUE TITLE
FYI: Node core issue on the way forward

### ISSUE THREAD

**Issue by addaleax** [AlexTes/buffer-deprecation#1]
Just in case you haven’t seen it, there’s https://github.com/nodejs/node/issues/9531 which you may want to keep an eye on, since you seem to be invested in this topic. (Maybe the future of `Buffer` in Node core isn’t a concern for you at all and you are only interested in the developer’s side of things, so feel free to ignore this! :smile:)

**Comment by alextes** [comment]
Hah, I wish I was in a position where I felt confident to discuss the future of `Buffer` in node 😅 . I'll definitely take a look!

**Comment by alextes** [comment]
😱 you're with the node foundation @addaleax! I'm so humbled you found my little write-up. If there was anything you thought should be rephrased or was plain wrong do tell of course! Otherwise thanks for the further reading. It interests me after the hours I spent trying to create a resource for other devs with the same question. I'll keep an eye on the issue you linked and will likely update when appropriate 😊 .

**Comment by addaleax** [comment]
Well, yeah, one of the problems we’re having is that our communication with module authors in the ecosystem is in pretty bad shape, so I’m trying to actively reach out to people when I see an opportunity.

So, yeah, please feel free to watch the discussion and please speak up if you think you have perspective to add there!

**Comment by alextes** [comment]
Will do @addaleax! I'll try and help whatever way I can. Node is <3.
